//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exec.Router {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Router.IRoutingServer")]
    public interface IRoutingServer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoutingServer/GetPath", ReplyAction="http://tempuri.org/IRoutingServer/GetPathResponse")]
        string GetPath(string start, string end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoutingServer/GetPath", ReplyAction="http://tempuri.org/IRoutingServer/GetPathResponse")]
        System.Threading.Tasks.Task<string> GetPathAsync(string start, string end);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRoutingServerChannel : Exec.Router.IRoutingServer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RoutingServerClient : System.ServiceModel.ClientBase<Exec.Router.IRoutingServer>, Exec.Router.IRoutingServer {
        
        public RoutingServerClient() {
        }
        
        public RoutingServerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RoutingServerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoutingServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoutingServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetPath(string start, string end) {
            return base.Channel.GetPath(start, end);
        }
        
        public System.Threading.Tasks.Task<string> GetPathAsync(string start, string end) {
            return base.Channel.GetPathAsync(start, end);
        }
    }
}
